/**
 * generated by Xtext 2.25.0
 */
package it.univaq.disim.housebuilder.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import it.univaq.disim.housebuilder.xtext.HouseBuilderRuntimeModule;
import it.univaq.disim.housebuilder.xtext.HouseBuilderStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class HouseBuilderIdeSetup extends HouseBuilderStandaloneSetup {
  @Override
  public Injector createInjector() {
    HouseBuilderRuntimeModule _houseBuilderRuntimeModule = new HouseBuilderRuntimeModule();
    HouseBuilderIdeModule _houseBuilderIdeModule = new HouseBuilderIdeModule();
    return Guice.createInjector(Modules2.mixin(_houseBuilderRuntimeModule, _houseBuilderIdeModule));
  }
}
