/*
 * generated by Xtext 2.25.0
 */
package it.univaq.disim.housebuilder.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractHouseBuilderV2ScopeProvider extends DelegatingScopeProvider {
}
