/**
 * generated by Xtext 2.25.0
 */
package it.univaq.disim.housebuilder.xtext;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class HouseBuilderStandaloneSetup extends HouseBuilderStandaloneSetupGenerated {
  public static void doSetup() {
    new HouseBuilderStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
