/*
 * generated by Xtext 2.25.0
 */
package it.univaq.disim.housebuilder.xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class HouseBuilderV2StandaloneSetup extends HouseBuilderV2StandaloneSetupGenerated {

	public static void doSetup() {
		new HouseBuilderV2StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
