/*
 * generated by Xtext 2.25.0
 */
package it.univaq.disim.housebuilder.xtext;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class HouseBuilderV2RuntimeModule extends AbstractHouseBuilderV2RuntimeModule {
}
