/*
 * generated by Xtext 2.25.0
 */
package it.univaq.disim.housebuilder.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class HouseBuilderStandaloneSetup extends HouseBuilderStandaloneSetupGenerated {

	def static void doSetup() {
		new HouseBuilderStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
