/*
 * generated by Xtext 2.25.0
 */
package it.univaq.disim.housebuilder.xtext.ide


/**
 * Use this class to register ide components.
 */
class HouseBuilderIdeModule extends AbstractHouseBuilderIdeModule {
}
