/*
 * generated by Xtext 2.25.0
 */
package it.univaq.disim.housebuilder.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import it.univaq.disim.housebuilder.xtext.HouseBuilderV2RuntimeModule;
import it.univaq.disim.housebuilder.xtext.HouseBuilderV2StandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class HouseBuilderV2IdeSetup extends HouseBuilderV2StandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new HouseBuilderV2RuntimeModule(), new HouseBuilderV2IdeModule()));
	}
	
}
