/*
 * generated by Xtext 2.25.0
 */
package it.univaq.disim.housebuilder.xtext.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import it.univaq.disim.housebuilder.xtext.ide.contentassist.antlr.internal.InternalHouseBuilderV2Parser;
import it.univaq.disim.housebuilder.xtext.services.HouseBuilderV2GrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class HouseBuilderV2Parser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(HouseBuilderV2GrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, HouseBuilderV2GrammarAccess grammarAccess) {
			builder.put(grammarAccess.getSpaceAccess().getAlternatives(), "rule__Space__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEFloatAccess().getAlternatives_4_0(), "rule__EFloat__Alternatives_4_0");
			builder.put(grammarAccess.getDeviceTypeAccess().getAlternatives(), "rule__DeviceType__Alternatives");
			builder.put(grammarAccess.getActuatorTypeAccess().getAlternatives(), "rule__ActuatorType__Alternatives");
			builder.put(grammarAccess.getSensorTypeAccess().getAlternatives(), "rule__SensorType__Alternatives");
			builder.put(grammarAccess.getRoomTypeAccess().getAlternatives(), "rule__RoomType__Alternatives");
			builder.put(grammarAccess.getOuterSpaceTypeAccess().getAlternatives(), "rule__OuterSpaceType__Alternatives");
			builder.put(grammarAccess.getGroundTypeAccess().getAlternatives(), "rule__GroundType__Alternatives");
			builder.put(grammarAccess.getDoorTypeAccess().getAlternatives(), "rule__DoorType__Alternatives");
			builder.put(grammarAccess.getHouseAccess().getGroup(), "rule__House__Group__0");
			builder.put(grammarAccess.getHouseAccess().getGroup_3(), "rule__House__Group_3__0");
			builder.put(grammarAccess.getHouseAccess().getGroup_4(), "rule__House__Group_4__0");
			builder.put(grammarAccess.getHouseAccess().getGroup_5(), "rule__House__Group_5__0");
			builder.put(grammarAccess.getHouseAccess().getGroup_6(), "rule__House__Group_6__0");
			builder.put(grammarAccess.getHouseAccess().getGroup_7(), "rule__House__Group_7__0");
			builder.put(grammarAccess.getHouseAccess().getGroup_8(), "rule__House__Group_8__0");
			builder.put(grammarAccess.getHouseAccess().getGroup_12(), "rule__House__Group_12__0");
			builder.put(grammarAccess.getHouseAccess().getGroup_14(), "rule__House__Group_14__0");
			builder.put(grammarAccess.getHouseAccess().getGroup_14_3(), "rule__House__Group_14_3__0");
			builder.put(grammarAccess.getHouseAccess().getGroup_15(), "rule__House__Group_15__0");
			builder.put(grammarAccess.getHouseAccess().getGroup_15_3(), "rule__House__Group_15_3__0");
			builder.put(grammarAccess.getHouseAccess().getGroup_19(), "rule__House__Group_19__0");
			builder.put(grammarAccess.getFloorAccess().getGroup(), "rule__Floor__Group__0");
			builder.put(grammarAccess.getFloorAccess().getGroup_8(), "rule__Floor__Group_8__0");
			builder.put(grammarAccess.getPassageAccess().getGroup(), "rule__Passage__Group__0");
			builder.put(grammarAccess.getPassageAccess().getGroup_15(), "rule__Passage__Group_15__0");
			builder.put(grammarAccess.getPassageAccess().getGroup_15_3(), "rule__Passage__Group_15_3__0");
			builder.put(grammarAccess.getControllerAccess().getGroup(), "rule__Controller__Group__0");
			builder.put(grammarAccess.getControllerAccess().getGroup_5(), "rule__Controller__Group_5__0");
			builder.put(grammarAccess.getControllerAccess().getGroup_6(), "rule__Controller__Group_6__0");
			builder.put(grammarAccess.getControllerAccess().getGroup_10(), "rule__Controller__Group_10__0");
			builder.put(grammarAccess.getControllerAccess().getGroup_15(), "rule__Controller__Group_15__0");
			builder.put(grammarAccess.getEntranceAccess().getGroup(), "rule__Entrance__Group__0");
			builder.put(grammarAccess.getEntranceAccess().getGroup_13(), "rule__Entrance__Group_13__0");
			builder.put(grammarAccess.getEntranceAccess().getGroup_13_3(), "rule__Entrance__Group_13_3__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getEFloatAccess().getGroup(), "rule__EFloat__Group__0");
			builder.put(grammarAccess.getEFloatAccess().getGroup_4(), "rule__EFloat__Group_4__0");
			builder.put(grammarAccess.getDeviceAccess().getGroup(), "rule__Device__Group__0");
			builder.put(grammarAccess.getDeviceAccess().getGroup_4(), "rule__Device__Group_4__0");
			builder.put(grammarAccess.getDeviceAccess().getGroup_5(), "rule__Device__Group_5__0");
			builder.put(grammarAccess.getDeviceAccess().getGroup_6(), "rule__Device__Group_6__0");
			builder.put(grammarAccess.getSensorAccess().getGroup(), "rule__Sensor__Group__0");
			builder.put(grammarAccess.getSensorAccess().getGroup_7(), "rule__Sensor__Group_7__0");
			builder.put(grammarAccess.getRoomAccess().getGroup(), "rule__Room__Group__0");
			builder.put(grammarAccess.getRoomAccess().getGroup_9(), "rule__Room__Group_9__0");
			builder.put(grammarAccess.getRoomAccess().getGroup_10(), "rule__Room__Group_10__0");
			builder.put(grammarAccess.getRoomAccess().getGroup_10_3(), "rule__Room__Group_10_3__0");
			builder.put(grammarAccess.getRoomAccess().getGroup_11(), "rule__Room__Group_11__0");
			builder.put(grammarAccess.getRoomAccess().getGroup_11_3(), "rule__Room__Group_11_3__0");
			builder.put(grammarAccess.getRoomAccess().getGroup_12(), "rule__Room__Group_12__0");
			builder.put(grammarAccess.getRoomAccess().getGroup_12_3(), "rule__Room__Group_12_3__0");
			builder.put(grammarAccess.getRoomAccess().getGroup_13(), "rule__Room__Group_13__0");
			builder.put(grammarAccess.getRoomAccess().getGroup_13_3(), "rule__Room__Group_13_3__0");
			builder.put(grammarAccess.getRoomAccess().getGroup_14(), "rule__Room__Group_14__0");
			builder.put(grammarAccess.getRoomAccess().getGroup_14_3(), "rule__Room__Group_14_3__0");
			builder.put(grammarAccess.getRoomAccess().getGroup_15(), "rule__Room__Group_15__0");
			builder.put(grammarAccess.getRoomAccess().getGroup_15_3(), "rule__Room__Group_15_3__0");
			builder.put(grammarAccess.getExternalSpaceAccess().getGroup(), "rule__ExternalSpace__Group__0");
			builder.put(grammarAccess.getExternalSpaceAccess().getGroup_7(), "rule__ExternalSpace__Group_7__0");
			builder.put(grammarAccess.getExternalSpaceAccess().getGroup_8(), "rule__ExternalSpace__Group_8__0");
			builder.put(grammarAccess.getExternalSpaceAccess().getGroup_9(), "rule__ExternalSpace__Group_9__0");
			builder.put(grammarAccess.getExternalSpaceAccess().getGroup_9_3(), "rule__ExternalSpace__Group_9_3__0");
			builder.put(grammarAccess.getExternalSpaceAccess().getGroup_10(), "rule__ExternalSpace__Group_10__0");
			builder.put(grammarAccess.getExternalSpaceAccess().getGroup_10_3(), "rule__ExternalSpace__Group_10_3__0");
			builder.put(grammarAccess.getExternalSpaceAccess().getGroup_11(), "rule__ExternalSpace__Group_11__0");
			builder.put(grammarAccess.getExternalSpaceAccess().getGroup_11_3(), "rule__ExternalSpace__Group_11_3__0");
			builder.put(grammarAccess.getExternalSpaceAccess().getGroup_12(), "rule__ExternalSpace__Group_12__0");
			builder.put(grammarAccess.getExternalSpaceAccess().getGroup_12_3(), "rule__ExternalSpace__Group_12_3__0");
			builder.put(grammarAccess.getExternalSpaceAccess().getGroup_13(), "rule__ExternalSpace__Group_13__0");
			builder.put(grammarAccess.getExternalSpaceAccess().getGroup_13_3(), "rule__ExternalSpace__Group_13_3__0");
			builder.put(grammarAccess.getActuatorAccess().getGroup(), "rule__Actuator__Group__0");
			builder.put(grammarAccess.getActuatorAccess().getGroup_5(), "rule__Actuator__Group_5__0");
			builder.put(grammarAccess.getWindowAccess().getGroup(), "rule__Window__Group__0");
			builder.put(grammarAccess.getHouseAccess().getNameAssignment_1(), "rule__House__NameAssignment_1");
			builder.put(grammarAccess.getHouseAccess().getStateAssignment_3_1(), "rule__House__StateAssignment_3_1");
			builder.put(grammarAccess.getHouseAccess().getProvinceAssignment_4_1(), "rule__House__ProvinceAssignment_4_1");
			builder.put(grammarAccess.getHouseAccess().getCityAssignment_5_1(), "rule__House__CityAssignment_5_1");
			builder.put(grammarAccess.getHouseAccess().getPostalCodeAssignment_6_1(), "rule__House__PostalCodeAssignment_6_1");
			builder.put(grammarAccess.getHouseAccess().getAddressAssignment_7_1(), "rule__House__AddressAssignment_7_1");
			builder.put(grammarAccess.getHouseAccess().getBuildingDateAssignment_8_1(), "rule__House__BuildingDateAssignment_8_1");
			builder.put(grammarAccess.getHouseAccess().getFloorsAssignment_11(), "rule__House__FloorsAssignment_11");
			builder.put(grammarAccess.getHouseAccess().getFloorsAssignment_12_1(), "rule__House__FloorsAssignment_12_1");
			builder.put(grammarAccess.getHouseAccess().getPassagesAssignment_14_2(), "rule__House__PassagesAssignment_14_2");
			builder.put(grammarAccess.getHouseAccess().getPassagesAssignment_14_3_1(), "rule__House__PassagesAssignment_14_3_1");
			builder.put(grammarAccess.getHouseAccess().getControllersAssignment_15_2(), "rule__House__ControllersAssignment_15_2");
			builder.put(grammarAccess.getHouseAccess().getControllersAssignment_15_3_1(), "rule__House__ControllersAssignment_15_3_1");
			builder.put(grammarAccess.getHouseAccess().getEntrancesAssignment_18(), "rule__House__EntrancesAssignment_18");
			builder.put(grammarAccess.getHouseAccess().getEntrancesAssignment_19_1(), "rule__House__EntrancesAssignment_19_1");
			builder.put(grammarAccess.getFloorAccess().getNameAssignment_1(), "rule__Floor__NameAssignment_1");
			builder.put(grammarAccess.getFloorAccess().getLevelAssignment_4(), "rule__Floor__LevelAssignment_4");
			builder.put(grammarAccess.getFloorAccess().getSpacesAssignment_7(), "rule__Floor__SpacesAssignment_7");
			builder.put(grammarAccess.getFloorAccess().getSpacesAssignment_8_1(), "rule__Floor__SpacesAssignment_8_1");
			builder.put(grammarAccess.getPassageAccess().getNameAssignment_1(), "rule__Passage__NameAssignment_1");
			builder.put(grammarAccess.getPassageAccess().getDoorTypeAssignment_4(), "rule__Passage__DoorTypeAssignment_4");
			builder.put(grammarAccess.getPassageAccess().getDoorsNumberAssignment_6(), "rule__Passage__DoorsNumberAssignment_6");
			builder.put(grammarAccess.getPassageAccess().getWidthAssignment_8(), "rule__Passage__WidthAssignment_8");
			builder.put(grammarAccess.getPassageAccess().getHeightAssignment_10(), "rule__Passage__HeightAssignment_10");
			builder.put(grammarAccess.getPassageAccess().getSpaceAAssignment_12(), "rule__Passage__SpaceAAssignment_12");
			builder.put(grammarAccess.getPassageAccess().getSpaceBAssignment_14(), "rule__Passage__SpaceBAssignment_14");
			builder.put(grammarAccess.getPassageAccess().getDevicesAssignment_15_2(), "rule__Passage__DevicesAssignment_15_2");
			builder.put(grammarAccess.getPassageAccess().getDevicesAssignment_15_3_1(), "rule__Passage__DevicesAssignment_15_3_1");
			builder.put(grammarAccess.getControllerAccess().getNameAssignment_1(), "rule__Controller__NameAssignment_1");
			builder.put(grammarAccess.getControllerAccess().getModelAssignment_4(), "rule__Controller__ModelAssignment_4");
			builder.put(grammarAccess.getControllerAccess().getOsAssignment_5_1(), "rule__Controller__OsAssignment_5_1");
			builder.put(grammarAccess.getControllerAccess().getOsVersionAssignment_6_1(), "rule__Controller__OsVersionAssignment_6_1");
			builder.put(grammarAccess.getControllerAccess().getActuatorsAssignment_9(), "rule__Controller__ActuatorsAssignment_9");
			builder.put(grammarAccess.getControllerAccess().getActuatorsAssignment_10_1(), "rule__Controller__ActuatorsAssignment_10_1");
			builder.put(grammarAccess.getControllerAccess().getSensorsAssignment_14(), "rule__Controller__SensorsAssignment_14");
			builder.put(grammarAccess.getControllerAccess().getSensorsAssignment_15_1(), "rule__Controller__SensorsAssignment_15_1");
			builder.put(grammarAccess.getEntranceAccess().getNameAssignment_1(), "rule__Entrance__NameAssignment_1");
			builder.put(grammarAccess.getEntranceAccess().getDoorTypeAssignment_4(), "rule__Entrance__DoorTypeAssignment_4");
			builder.put(grammarAccess.getEntranceAccess().getDoorsNumberAssignment_6(), "rule__Entrance__DoorsNumberAssignment_6");
			builder.put(grammarAccess.getEntranceAccess().getWidthAssignment_8(), "rule__Entrance__WidthAssignment_8");
			builder.put(grammarAccess.getEntranceAccess().getHeightAssignment_10(), "rule__Entrance__HeightAssignment_10");
			builder.put(grammarAccess.getEntranceAccess().getSpaceAssignment_12(), "rule__Entrance__SpaceAssignment_12");
			builder.put(grammarAccess.getEntranceAccess().getDevicesAssignment_13_2(), "rule__Entrance__DevicesAssignment_13_2");
			builder.put(grammarAccess.getEntranceAccess().getDevicesAssignment_13_3_1(), "rule__Entrance__DevicesAssignment_13_3_1");
			builder.put(grammarAccess.getDeviceAccess().getNameAssignment_2(), "rule__Device__NameAssignment_2");
			builder.put(grammarAccess.getDeviceAccess().getTypeAssignment_4_1(), "rule__Device__TypeAssignment_4_1");
			builder.put(grammarAccess.getDeviceAccess().getModelAssignment_5_1(), "rule__Device__ModelAssignment_5_1");
			builder.put(grammarAccess.getDeviceAccess().getActuatorAssignment_6_1(), "rule__Device__ActuatorAssignment_6_1");
			builder.put(grammarAccess.getSensorAccess().getNameAssignment_1(), "rule__Sensor__NameAssignment_1");
			builder.put(grammarAccess.getSensorAccess().getTypeAssignment_4(), "rule__Sensor__TypeAssignment_4");
			builder.put(grammarAccess.getSensorAccess().getValueAssignment_6(), "rule__Sensor__ValueAssignment_6");
			builder.put(grammarAccess.getSensorAccess().getModelAssignment_7_1(), "rule__Sensor__ModelAssignment_7_1");
			builder.put(grammarAccess.getSensorAccess().getSpaceAssignment_9(), "rule__Sensor__SpaceAssignment_9");
			builder.put(grammarAccess.getRoomAccess().getNameAssignment_1(), "rule__Room__NameAssignment_1");
			builder.put(grammarAccess.getRoomAccess().getLengthAssignment_4(), "rule__Room__LengthAssignment_4");
			builder.put(grammarAccess.getRoomAccess().getWidthAssignment_6(), "rule__Room__WidthAssignment_6");
			builder.put(grammarAccess.getRoomAccess().getHeightAssignment_8(), "rule__Room__HeightAssignment_8");
			builder.put(grammarAccess.getRoomAccess().getRoomTypeAssignment_9_1(), "rule__Room__RoomTypeAssignment_9_1");
			builder.put(grammarAccess.getRoomAccess().getSensorsAssignment_10_2(), "rule__Room__SensorsAssignment_10_2");
			builder.put(grammarAccess.getRoomAccess().getSensorsAssignment_10_3_1(), "rule__Room__SensorsAssignment_10_3_1");
			builder.put(grammarAccess.getRoomAccess().getPassagesAAssignment_11_2(), "rule__Room__PassagesAAssignment_11_2");
			builder.put(grammarAccess.getRoomAccess().getPassagesAAssignment_11_3_1(), "rule__Room__PassagesAAssignment_11_3_1");
			builder.put(grammarAccess.getRoomAccess().getPassagesBAssignment_12_2(), "rule__Room__PassagesBAssignment_12_2");
			builder.put(grammarAccess.getRoomAccess().getPassagesBAssignment_12_3_1(), "rule__Room__PassagesBAssignment_12_3_1");
			builder.put(grammarAccess.getRoomAccess().getEntrancesAssignment_13_2(), "rule__Room__EntrancesAssignment_13_2");
			builder.put(grammarAccess.getRoomAccess().getEntrancesAssignment_13_3_1(), "rule__Room__EntrancesAssignment_13_3_1");
			builder.put(grammarAccess.getRoomAccess().getDevicesAssignment_14_2(), "rule__Room__DevicesAssignment_14_2");
			builder.put(grammarAccess.getRoomAccess().getDevicesAssignment_14_3_1(), "rule__Room__DevicesAssignment_14_3_1");
			builder.put(grammarAccess.getRoomAccess().getWindowsAssignment_15_2(), "rule__Room__WindowsAssignment_15_2");
			builder.put(grammarAccess.getRoomAccess().getWindowsAssignment_15_3_1(), "rule__Room__WindowsAssignment_15_3_1");
			builder.put(grammarAccess.getExternalSpaceAccess().getNameAssignment_1(), "rule__ExternalSpace__NameAssignment_1");
			builder.put(grammarAccess.getExternalSpaceAccess().getLengthAssignment_4(), "rule__ExternalSpace__LengthAssignment_4");
			builder.put(grammarAccess.getExternalSpaceAccess().getWidthAssignment_6(), "rule__ExternalSpace__WidthAssignment_6");
			builder.put(grammarAccess.getExternalSpaceAccess().getTypeAssignment_7_1(), "rule__ExternalSpace__TypeAssignment_7_1");
			builder.put(grammarAccess.getExternalSpaceAccess().getGroundAssignment_8_1(), "rule__ExternalSpace__GroundAssignment_8_1");
			builder.put(grammarAccess.getExternalSpaceAccess().getSensorsAssignment_9_2(), "rule__ExternalSpace__SensorsAssignment_9_2");
			builder.put(grammarAccess.getExternalSpaceAccess().getSensorsAssignment_9_3_1(), "rule__ExternalSpace__SensorsAssignment_9_3_1");
			builder.put(grammarAccess.getExternalSpaceAccess().getPassagesAAssignment_10_2(), "rule__ExternalSpace__PassagesAAssignment_10_2");
			builder.put(grammarAccess.getExternalSpaceAccess().getPassagesAAssignment_10_3_1(), "rule__ExternalSpace__PassagesAAssignment_10_3_1");
			builder.put(grammarAccess.getExternalSpaceAccess().getPassagesBAssignment_11_2(), "rule__ExternalSpace__PassagesBAssignment_11_2");
			builder.put(grammarAccess.getExternalSpaceAccess().getPassagesBAssignment_11_3_1(), "rule__ExternalSpace__PassagesBAssignment_11_3_1");
			builder.put(grammarAccess.getExternalSpaceAccess().getEntrancesAssignment_12_2(), "rule__ExternalSpace__EntrancesAssignment_12_2");
			builder.put(grammarAccess.getExternalSpaceAccess().getEntrancesAssignment_12_3_1(), "rule__ExternalSpace__EntrancesAssignment_12_3_1");
			builder.put(grammarAccess.getExternalSpaceAccess().getDevicesAssignment_13_2(), "rule__ExternalSpace__DevicesAssignment_13_2");
			builder.put(grammarAccess.getExternalSpaceAccess().getDevicesAssignment_13_3_1(), "rule__ExternalSpace__DevicesAssignment_13_3_1");
			builder.put(grammarAccess.getActuatorAccess().getNameAssignment_1(), "rule__Actuator__NameAssignment_1");
			builder.put(grammarAccess.getActuatorAccess().getTypeAssignment_4(), "rule__Actuator__TypeAssignment_4");
			builder.put(grammarAccess.getActuatorAccess().getModelAssignment_5_1(), "rule__Actuator__ModelAssignment_5_1");
			builder.put(grammarAccess.getActuatorAccess().getDeviceAssignment_7(), "rule__Actuator__DeviceAssignment_7");
			builder.put(grammarAccess.getWindowAccess().getNameAssignment_1(), "rule__Window__NameAssignment_1");
			builder.put(grammarAccess.getWindowAccess().getDoorsNumberAssignment_4(), "rule__Window__DoorsNumberAssignment_4");
			builder.put(grammarAccess.getWindowAccess().getWidthAssignment_6(), "rule__Window__WidthAssignment_6");
			builder.put(grammarAccess.getWindowAccess().getHeightAssignment_8(), "rule__Window__HeightAssignment_8");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private HouseBuilderV2GrammarAccess grammarAccess;

	@Override
	protected InternalHouseBuilderV2Parser createParser() {
		InternalHouseBuilderV2Parser result = new InternalHouseBuilderV2Parser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public HouseBuilderV2GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(HouseBuilderV2GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
