/*
 * generated by Xtext 2.25.0
 */
package it.univaq.disim.housebuilder.xtext.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import it.univaq.disim.housebuilder.xtext.ide.contentassist.antlr.internal.InternalHouseBuilderParser;
import it.univaq.disim.housebuilder.xtext.services.HouseBuilderGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class HouseBuilderParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(HouseBuilderGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, HouseBuilderGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getSpaceAccess().getAlternatives(), "rule__Space__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEFloatAccess().getAlternatives_4_0(), "rule__EFloat__Alternatives_4_0");
			builder.put(grammarAccess.getDeviceTypeAccess().getAlternatives(), "rule__DeviceType__Alternatives");
			builder.put(grammarAccess.getActuatorTypeAccess().getAlternatives(), "rule__ActuatorType__Alternatives");
			builder.put(grammarAccess.getSensorTypeAccess().getAlternatives(), "rule__SensorType__Alternatives");
			builder.put(grammarAccess.getRoomTypeAccess().getAlternatives(), "rule__RoomType__Alternatives");
			builder.put(grammarAccess.getExternalSpaceTypeAccess().getAlternatives(), "rule__ExternalSpaceType__Alternatives");
			builder.put(grammarAccess.getGroundTypeAccess().getAlternatives(), "rule__GroundType__Alternatives");
			builder.put(grammarAccess.getDoorTypeAccess().getAlternatives(), "rule__DoorType__Alternatives");
			builder.put(grammarAccess.getHouseAccess().getGroup(), "rule__House__Group__0");
			builder.put(grammarAccess.getHouseAccess().getGroup_3(), "rule__House__Group_3__0");
			builder.put(grammarAccess.getHouseAccess().getGroup_4(), "rule__House__Group_4__0");
			builder.put(grammarAccess.getHouseAccess().getGroup_5(), "rule__House__Group_5__0");
			builder.put(grammarAccess.getHouseAccess().getGroup_6(), "rule__House__Group_6__0");
			builder.put(grammarAccess.getHouseAccess().getGroup_7(), "rule__House__Group_7__0");
			builder.put(grammarAccess.getHouseAccess().getGroup_8(), "rule__House__Group_8__0");
			builder.put(grammarAccess.getHouseAccess().getGroup_12(), "rule__House__Group_12__0");
			builder.put(grammarAccess.getHouseAccess().getGroup_17(), "rule__House__Group_17__0");
			builder.put(grammarAccess.getHouseAccess().getGroup_19(), "rule__House__Group_19__0");
			builder.put(grammarAccess.getHouseAccess().getGroup_19_3(), "rule__House__Group_19_3__0");
			builder.put(grammarAccess.getHouseAccess().getGroup_20(), "rule__House__Group_20__0");
			builder.put(grammarAccess.getHouseAccess().getGroup_20_3(), "rule__House__Group_20_3__0");
			builder.put(grammarAccess.getFloorAccess().getGroup(), "rule__Floor__Group__0");
			builder.put(grammarAccess.getFloorAccess().getGroup_8(), "rule__Floor__Group_8__0");
			builder.put(grammarAccess.getPassageAccess().getGroup(), "rule__Passage__Group__0");
			builder.put(grammarAccess.getPassageAccess().getGroup_3(), "rule__Passage__Group_3__0");
			builder.put(grammarAccess.getPassageAccess().getGroup_4(), "rule__Passage__Group_4__0");
			builder.put(grammarAccess.getPassageAccess().getGroup_5(), "rule__Passage__Group_5__0");
			builder.put(grammarAccess.getPassageAccess().getGroup_10(), "rule__Passage__Group_10__0");
			builder.put(grammarAccess.getPassageAccess().getGroup_10_3(), "rule__Passage__Group_10_3__0");
			builder.put(grammarAccess.getControllerAccess().getGroup(), "rule__Controller__Group__0");
			builder.put(grammarAccess.getControllerAccess().getGroup_3(), "rule__Controller__Group_3__0");
			builder.put(grammarAccess.getControllerAccess().getGroup_4(), "rule__Controller__Group_4__0");
			builder.put(grammarAccess.getControllerAccess().getGroup_5(), "rule__Controller__Group_5__0");
			builder.put(grammarAccess.getControllerAccess().getGroup_9(), "rule__Controller__Group_9__0");
			builder.put(grammarAccess.getControllerAccess().getGroup_14(), "rule__Controller__Group_14__0");
			builder.put(grammarAccess.getEntranceAccess().getGroup(), "rule__Entrance__Group__0");
			builder.put(grammarAccess.getEntranceAccess().getGroup_3(), "rule__Entrance__Group_3__0");
			builder.put(grammarAccess.getEntranceAccess().getGroup_4(), "rule__Entrance__Group_4__0");
			builder.put(grammarAccess.getEntranceAccess().getGroup_5(), "rule__Entrance__Group_5__0");
			builder.put(grammarAccess.getEntranceAccess().getGroup_8(), "rule__Entrance__Group_8__0");
			builder.put(grammarAccess.getEntranceAccess().getGroup_8_3(), "rule__Entrance__Group_8_3__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getEFloatAccess().getGroup(), "rule__EFloat__Group__0");
			builder.put(grammarAccess.getEFloatAccess().getGroup_4(), "rule__EFloat__Group_4__0");
			builder.put(grammarAccess.getDeviceAccess().getGroup(), "rule__Device__Group__0");
			builder.put(grammarAccess.getDeviceAccess().getGroup_4(), "rule__Device__Group_4__0");
			builder.put(grammarAccess.getDeviceAccess().getGroup_5(), "rule__Device__Group_5__0");
			builder.put(grammarAccess.getSensorAccess().getGroup(), "rule__Sensor__Group__0");
			builder.put(grammarAccess.getSensorAccess().getGroup_3(), "rule__Sensor__Group_3__0");
			builder.put(grammarAccess.getSensorAccess().getGroup_4(), "rule__Sensor__Group_4__0");
			builder.put(grammarAccess.getSensorAccess().getGroup_5(), "rule__Sensor__Group_5__0");
			builder.put(grammarAccess.getRoomAccess().getGroup(), "rule__Room__Group__0");
			builder.put(grammarAccess.getRoomAccess().getGroup_7(), "rule__Room__Group_7__0");
			builder.put(grammarAccess.getRoomAccess().getGroup_8(), "rule__Room__Group_8__0");
			builder.put(grammarAccess.getRoomAccess().getGroup_9(), "rule__Room__Group_9__0");
			builder.put(grammarAccess.getRoomAccess().getGroup_9_3(), "rule__Room__Group_9_3__0");
			builder.put(grammarAccess.getRoomAccess().getGroup_10(), "rule__Room__Group_10__0");
			builder.put(grammarAccess.getRoomAccess().getGroup_10_3(), "rule__Room__Group_10_3__0");
			builder.put(grammarAccess.getExternalSpaceAccess().getGroup(), "rule__ExternalSpace__Group__0");
			builder.put(grammarAccess.getExternalSpaceAccess().getGroup_9(), "rule__ExternalSpace__Group_9__0");
			builder.put(grammarAccess.getExternalSpaceAccess().getGroup_10(), "rule__ExternalSpace__Group_10__0");
			builder.put(grammarAccess.getExternalSpaceAccess().getGroup_10_3(), "rule__ExternalSpace__Group_10_3__0");
			builder.put(grammarAccess.getActuatorAccess().getGroup(), "rule__Actuator__Group__0");
			builder.put(grammarAccess.getActuatorAccess().getGroup_3(), "rule__Actuator__Group_3__0");
			builder.put(grammarAccess.getActuatorAccess().getGroup_4(), "rule__Actuator__Group_4__0");
			builder.put(grammarAccess.getWindowAccess().getGroup(), "rule__Window__Group__0");
			builder.put(grammarAccess.getWindowAccess().getGroup_4(), "rule__Window__Group_4__0");
			builder.put(grammarAccess.getWindowAccess().getGroup_5(), "rule__Window__Group_5__0");
			builder.put(grammarAccess.getHouseAccess().getNameAssignment_1(), "rule__House__NameAssignment_1");
			builder.put(grammarAccess.getHouseAccess().getStateAssignment_3_1(), "rule__House__StateAssignment_3_1");
			builder.put(grammarAccess.getHouseAccess().getProvinceAssignment_4_1(), "rule__House__ProvinceAssignment_4_1");
			builder.put(grammarAccess.getHouseAccess().getCityAssignment_5_1(), "rule__House__CityAssignment_5_1");
			builder.put(grammarAccess.getHouseAccess().getPostalCodeAssignment_6_1(), "rule__House__PostalCodeAssignment_6_1");
			builder.put(grammarAccess.getHouseAccess().getAddressAssignment_7_1(), "rule__House__AddressAssignment_7_1");
			builder.put(grammarAccess.getHouseAccess().getBuildingDateAssignment_8_1(), "rule__House__BuildingDateAssignment_8_1");
			builder.put(grammarAccess.getHouseAccess().getFloorsAssignment_11(), "rule__House__FloorsAssignment_11");
			builder.put(grammarAccess.getHouseAccess().getFloorsAssignment_12_1(), "rule__House__FloorsAssignment_12_1");
			builder.put(grammarAccess.getHouseAccess().getEntrancesAssignment_16(), "rule__House__EntrancesAssignment_16");
			builder.put(grammarAccess.getHouseAccess().getEntrancesAssignment_17_1(), "rule__House__EntrancesAssignment_17_1");
			builder.put(grammarAccess.getHouseAccess().getPassagesAssignment_19_2(), "rule__House__PassagesAssignment_19_2");
			builder.put(grammarAccess.getHouseAccess().getPassagesAssignment_19_3_1(), "rule__House__PassagesAssignment_19_3_1");
			builder.put(grammarAccess.getHouseAccess().getControllersAssignment_20_2(), "rule__House__ControllersAssignment_20_2");
			builder.put(grammarAccess.getHouseAccess().getControllersAssignment_20_3_1(), "rule__House__ControllersAssignment_20_3_1");
			builder.put(grammarAccess.getFloorAccess().getNameAssignment_1(), "rule__Floor__NameAssignment_1");
			builder.put(grammarAccess.getFloorAccess().getLevelAssignment_4(), "rule__Floor__LevelAssignment_4");
			builder.put(grammarAccess.getFloorAccess().getSpacesAssignment_7(), "rule__Floor__SpacesAssignment_7");
			builder.put(grammarAccess.getFloorAccess().getSpacesAssignment_8_1(), "rule__Floor__SpacesAssignment_8_1");
			builder.put(grammarAccess.getPassageAccess().getNameAssignment_1(), "rule__Passage__NameAssignment_1");
			builder.put(grammarAccess.getPassageAccess().getDoorTypeAssignment_3_1(), "rule__Passage__DoorTypeAssignment_3_1");
			builder.put(grammarAccess.getPassageAccess().getDoorsNumberAssignment_4_1(), "rule__Passage__DoorsNumberAssignment_4_1");
			builder.put(grammarAccess.getPassageAccess().getHeightAssignment_5_1(), "rule__Passage__HeightAssignment_5_1");
			builder.put(grammarAccess.getPassageAccess().getWidthAssignment_5_3(), "rule__Passage__WidthAssignment_5_3");
			builder.put(grammarAccess.getPassageAccess().getSpaceAAssignment_7(), "rule__Passage__SpaceAAssignment_7");
			builder.put(grammarAccess.getPassageAccess().getSpaceBAssignment_9(), "rule__Passage__SpaceBAssignment_9");
			builder.put(grammarAccess.getPassageAccess().getDevicesAssignment_10_2(), "rule__Passage__DevicesAssignment_10_2");
			builder.put(grammarAccess.getPassageAccess().getDevicesAssignment_10_3_1(), "rule__Passage__DevicesAssignment_10_3_1");
			builder.put(grammarAccess.getControllerAccess().getNameAssignment_1(), "rule__Controller__NameAssignment_1");
			builder.put(grammarAccess.getControllerAccess().getModelAssignment_3_1(), "rule__Controller__ModelAssignment_3_1");
			builder.put(grammarAccess.getControllerAccess().getOsAssignment_4_1(), "rule__Controller__OsAssignment_4_1");
			builder.put(grammarAccess.getControllerAccess().getOsVersionAssignment_5_1(), "rule__Controller__OsVersionAssignment_5_1");
			builder.put(grammarAccess.getControllerAccess().getActuatorsAssignment_8(), "rule__Controller__ActuatorsAssignment_8");
			builder.put(grammarAccess.getControllerAccess().getActuatorsAssignment_9_1(), "rule__Controller__ActuatorsAssignment_9_1");
			builder.put(grammarAccess.getControllerAccess().getSensorsAssignment_13(), "rule__Controller__SensorsAssignment_13");
			builder.put(grammarAccess.getControllerAccess().getSensorsAssignment_14_1(), "rule__Controller__SensorsAssignment_14_1");
			builder.put(grammarAccess.getEntranceAccess().getNameAssignment_1(), "rule__Entrance__NameAssignment_1");
			builder.put(grammarAccess.getEntranceAccess().getDoorTypeAssignment_3_1(), "rule__Entrance__DoorTypeAssignment_3_1");
			builder.put(grammarAccess.getEntranceAccess().getDoorsNumberAssignment_4_1(), "rule__Entrance__DoorsNumberAssignment_4_1");
			builder.put(grammarAccess.getEntranceAccess().getHeightAssignment_5_1(), "rule__Entrance__HeightAssignment_5_1");
			builder.put(grammarAccess.getEntranceAccess().getWidthAssignment_5_3(), "rule__Entrance__WidthAssignment_5_3");
			builder.put(grammarAccess.getEntranceAccess().getSpaceAssignment_7(), "rule__Entrance__SpaceAssignment_7");
			builder.put(grammarAccess.getEntranceAccess().getDevicesAssignment_8_2(), "rule__Entrance__DevicesAssignment_8_2");
			builder.put(grammarAccess.getEntranceAccess().getDevicesAssignment_8_3_1(), "rule__Entrance__DevicesAssignment_8_3_1");
			builder.put(grammarAccess.getDeviceAccess().getNameAssignment_2(), "rule__Device__NameAssignment_2");
			builder.put(grammarAccess.getDeviceAccess().getTypeAssignment_4_1(), "rule__Device__TypeAssignment_4_1");
			builder.put(grammarAccess.getDeviceAccess().getModelAssignment_5_1(), "rule__Device__ModelAssignment_5_1");
			builder.put(grammarAccess.getSensorAccess().getNameAssignment_1(), "rule__Sensor__NameAssignment_1");
			builder.put(grammarAccess.getSensorAccess().getTypeAssignment_3_1(), "rule__Sensor__TypeAssignment_3_1");
			builder.put(grammarAccess.getSensorAccess().getValueAssignment_4_1(), "rule__Sensor__ValueAssignment_4_1");
			builder.put(grammarAccess.getSensorAccess().getModelAssignment_5_1(), "rule__Sensor__ModelAssignment_5_1");
			builder.put(grammarAccess.getSensorAccess().getSpaceAssignment_7(), "rule__Sensor__SpaceAssignment_7");
			builder.put(grammarAccess.getRoomAccess().getNameAssignment_1(), "rule__Room__NameAssignment_1");
			builder.put(grammarAccess.getRoomAccess().getLengthAssignment_4(), "rule__Room__LengthAssignment_4");
			builder.put(grammarAccess.getRoomAccess().getWidthAssignment_6(), "rule__Room__WidthAssignment_6");
			builder.put(grammarAccess.getRoomAccess().getHeightAssignment_7_1(), "rule__Room__HeightAssignment_7_1");
			builder.put(grammarAccess.getRoomAccess().getRoomTypeAssignment_8_1(), "rule__Room__RoomTypeAssignment_8_1");
			builder.put(grammarAccess.getRoomAccess().getDevicesAssignment_9_2(), "rule__Room__DevicesAssignment_9_2");
			builder.put(grammarAccess.getRoomAccess().getDevicesAssignment_9_3_1(), "rule__Room__DevicesAssignment_9_3_1");
			builder.put(grammarAccess.getRoomAccess().getWindowsAssignment_10_2(), "rule__Room__WindowsAssignment_10_2");
			builder.put(grammarAccess.getRoomAccess().getWindowsAssignment_10_3_1(), "rule__Room__WindowsAssignment_10_3_1");
			builder.put(grammarAccess.getExternalSpaceAccess().getNameAssignment_1(), "rule__ExternalSpace__NameAssignment_1");
			builder.put(grammarAccess.getExternalSpaceAccess().getLengthAssignment_4(), "rule__ExternalSpace__LengthAssignment_4");
			builder.put(grammarAccess.getExternalSpaceAccess().getWidthAssignment_6(), "rule__ExternalSpace__WidthAssignment_6");
			builder.put(grammarAccess.getExternalSpaceAccess().getTypeAssignment_8(), "rule__ExternalSpace__TypeAssignment_8");
			builder.put(grammarAccess.getExternalSpaceAccess().getGroundAssignment_9_1(), "rule__ExternalSpace__GroundAssignment_9_1");
			builder.put(grammarAccess.getExternalSpaceAccess().getDevicesAssignment_10_2(), "rule__ExternalSpace__DevicesAssignment_10_2");
			builder.put(grammarAccess.getExternalSpaceAccess().getDevicesAssignment_10_3_1(), "rule__ExternalSpace__DevicesAssignment_10_3_1");
			builder.put(grammarAccess.getActuatorAccess().getNameAssignment_1(), "rule__Actuator__NameAssignment_1");
			builder.put(grammarAccess.getActuatorAccess().getTypeAssignment_3_1(), "rule__Actuator__TypeAssignment_3_1");
			builder.put(grammarAccess.getActuatorAccess().getModelAssignment_4_1(), "rule__Actuator__ModelAssignment_4_1");
			builder.put(grammarAccess.getActuatorAccess().getDeviceAssignment_6(), "rule__Actuator__DeviceAssignment_6");
			builder.put(grammarAccess.getWindowAccess().getNameAssignment_2(), "rule__Window__NameAssignment_2");
			builder.put(grammarAccess.getWindowAccess().getDoorsNumberAssignment_4_1(), "rule__Window__DoorsNumberAssignment_4_1");
			builder.put(grammarAccess.getWindowAccess().getHeightAssignment_5_1(), "rule__Window__HeightAssignment_5_1");
			builder.put(grammarAccess.getWindowAccess().getWidthAssignment_5_3(), "rule__Window__WidthAssignment_5_3");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private HouseBuilderGrammarAccess grammarAccess;

	@Override
	protected InternalHouseBuilderParser createParser() {
		InternalHouseBuilderParser result = new InternalHouseBuilderParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public HouseBuilderGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(HouseBuilderGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
