/*
 * generated by Xtext 2.25.0
 */
package it.univaq.disim.housebuilder.xtext.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class HouseBuilderUiModule extends AbstractHouseBuilderUiModule {
}
