/*
 * generated by Xtext 2.25.0
 */
package it.univaq.disim.housebuilder.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class HouseBuilderV2UiModule extends AbstractHouseBuilderV2UiModule {

	public HouseBuilderV2UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
