/*
 * generated by Xtext 2.25.0
 */
package it.univaq.disim.housebuilder.xtext.parser.antlr;

import com.google.inject.Inject;
import it.univaq.disim.housebuilder.xtext.parser.antlr.internal.InternalHouseBuilderParser;
import it.univaq.disim.housebuilder.xtext.services.HouseBuilderGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class HouseBuilderParser extends AbstractAntlrParser {

	@Inject
	private HouseBuilderGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalHouseBuilderParser createParser(XtextTokenStream stream) {
		return new InternalHouseBuilderParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "House";
	}

	public HouseBuilderGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(HouseBuilderGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
