/*
 * generated by Xtext 2.25.0
 */
package it.univaq.disim.housebuilder.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class HouseBuilderAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("it/univaq/disim/housebuilder/xtext/parser/antlr/internal/InternalHouseBuilder.tokens");
	}
}
