/*
 * generated by Xtext 2.25.0
 */
package it.univaq.disim.housebuilder.xtext.parser.antlr;

import com.google.inject.Inject;
import it.univaq.disim.housebuilder.xtext.parser.antlr.internal.InternalHouseBuilderV2Parser;
import it.univaq.disim.housebuilder.xtext.services.HouseBuilderV2GrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class HouseBuilderV2Parser extends AbstractAntlrParser {

	@Inject
	private HouseBuilderV2GrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalHouseBuilderV2Parser createParser(XtextTokenStream stream) {
		return new InternalHouseBuilderV2Parser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "House";
	}

	public HouseBuilderV2GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(HouseBuilderV2GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
