/*
 * generated by Xtext 2.25.0
 */
package it.univaq.disim.housebuilder.xtext.ui;

import com.google.inject.Injector;
import it.univaq.disim.housebuilder.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class HouseBuilderV2ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(XtextActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		XtextActivator activator = XtextActivator.getInstance();
		return activator != null ? activator.getInjector(XtextActivator.IT_UNIVAQ_DISIM_HOUSEBUILDER_XTEXT_HOUSEBUILDERV2) : null;
	}

}
