/*
 * generated by Xtext 2.25.0
 */
package it.univaq.disim.housebuilder.xtext.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class HouseBuilderV2ProposalProvider extends AbstractHouseBuilderV2ProposalProvider {
}
