/*
 * generated by Xtext 2.25.0
 */
package it.univaq.disim.housebuilder.xtext.validation;


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class HouseBuilderV2Validator extends AbstractHouseBuilderV2Validator {
	
//	public static final String INVALID_NAME = "invalidName";
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					HouseBuilderV2Package.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}
	
}
